services:
  nginx:
    image: nginx:1.27-alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "20MB"

  api1:
    image: ghcr.io/obrunogonzaga/rinha-fraud-rust:v0.1.0
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "165MB"

  api2:
    image: ghcr.io/obrunogonzaga/rinha-fraud-rust:v0.1.0
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "165MB"

networks:
  default:
    driver: bridge
